Lecture 1 setup and product dao
Dima-Makarov/phoneshop-servlet-api pull request #1
Opened 2022-01-27 12:42 UTC by Dima-Makarov

2022-01-27 20:36 UTC, WladyslawDryhill requested changes
Добавил немного комментов

2022-01-27 20:36 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        save(new Product("sgs", "Samsung Galaxy S", new BigDecimal(100), usd, 100, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufacturer/Samsung/Samsung%20Galaxy%
Замени тут пожалуйста урлы картинок на относительные наподобие manufacturer/Samsung/Samsung%20Galaxy%20S%20II.jpg т.к. в JSP продукт лист страницы уже содержится базовый урл и картинки не отображаются

2022-01-27 20:36 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .get();
Давай здесь лучше вместо эксепшена возвращать Optional<Product>, и потом уже на уровне сервлета будем обрабатывать этот кейс.

2022-01-27 20:36 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    synchronized public Product getProduct(Long id) throws NoSuchElementException {
Вариант с synchronized конечно рабочий, однако в данном случае любые параллельные операции чтения и записи будут блочить друг друга т.к. требуют один и тот же монитор. Если есть желание и время предлагаю здесь использовать ReadWriteLock, readLock для операций чтения и writeLock для операций записи. В таком случае операции чтения смогут происходить параллельно и не блокировать друг друга

2022-01-27 20:36 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    synchronized public List<Product> findProducts() {
^ также как вариант использовать readLock

2022-01-27 20:36 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    synchronized public void save(Product product) {
^ а здесь writeLock

2022-01-27 20:36 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    synchronized public void delete(Long id) {
^ и здесь writeLock

2022-01-27 20:36 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        return products.stream()
Я бы еще на всякий случай добавил проверку на null перед циклом и получением lock-а и возвращал сразу Optional.empty()

2022-01-27 20:36 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        Optional<Product> p = products.stream()
Тут более компактно использовать Collection#removeIf

2022-01-27 20:36 UTC, WladyslawDryhill commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertTrue(productDao.findProducts().contains(p));
Вместо findProducts чуть эффективнее использовать getProduct(...) по сгенерированному id

2022-01-28 07:35 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        save(new Product("sgs", "Samsung Galaxy S", new BigDecimal(100), usd, 100, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufacturer/Samsung/Samsung%20Galaxy%
Заменил

2022-01-28 07:35 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .get();
Сделал

2022-01-28 07:35 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    synchronized public Product getProduct(Long id) throws NoSuchElementException {
Переписал на ReadWriteLock

2022-01-28 07:35 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        return products.stream()
Сделал

2022-01-28 07:35 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        Optional<Product> p = products.stream()
Да, сделал так

2022-01-28 07:36 UTC, Dima-Makarov commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertTrue(productDao.findProducts().contains(p));
Сделал

2022-01-28 13:12 UTC, WladyslawDryhill requested changes
Еще чуть-чуть

2022-01-28 13:12 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        synchronized (lock.readLock()) {
Тут во всех методах немного неправильное использование ReadWriteLock-a. В конструкции с synchronized(lock) все равно операции чтения будут блокировать друг друга. У локов есть свой собственный метод lock() который содержит логику по правильному контролю доступа потоков. Отрефактори пожалуйста использования локов следующим образом:

lock.readLock() / writeLock().lock();
try {
  // основная логика
} finally {
  lock.readLock() / writeLock().unlock();
}

finally здесь необходим для избегания ситуаций когда во вложенных методах падают unchecked исключения и в отличие от synchronized данный лок продолжает оставаться занятым.

2022-01-28 13:12 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
>      public void delete(Long id) {
Ну и давай еще тут проверочку на null добавим, чтоб совсем идеально было)

2022-01-28 13:33 UTC, merged