Lecture 2 search and sort
Dima-Makarov/phoneshop-servlet-api pull request #2
Opened 2022-01-30 08:56 UTC by Dima-Makarov

2022-02-01 19:16 UTC, WladyslawDryhill commented
пофикси пожалуйста коммиты в этой ветке, вижу много лишних коммитов и еще merge commit из мастера

2022-02-01 19:39 UTC, WladyslawDryhill requested changes

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                    .filter(product -> {
такую длинную логику в фильтре лучше выносить в отдельный метод, а еще лучше сделать составной фильтр вместе с сток/прайс чтобы отфильтровать в один цикл, например через Predicate#and. советую вынести логику по получению предиката в зависимости от входных параметров в отдельный метод

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                        String[] productWords = product.getDescription().split(" ");
думаю здесь нет смысла увеличивать количество итераций и разбивать дескрипшн на слова, contains должен правильно отработать и без этого

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                        for (String i : queryWordsList) {
попробуй переписать на стримах

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                    .sorted((Product a, Product b) -> {
эта сортировка должна быть взаимоисключаема с сортировкой по sort параметрам, либо должен создаваться комплексный компаратор через Comparator#thenComparing. а у тебя продукты дважды полностью сортируются

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                            for (String j : a.getDescription().split(" ")) {
и тут должно сработать без сплита, обычный contains подойдет по всему дескрипшену

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                            for (String j : b.getDescription().split(" ")) {
^ и тут тоже, как и в комменте выше

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                        } else if (sortField == SortField.description) {
можно попробовать сделать более расшрияемо используя EnumMap, где ключом будет SortField, а значением Comparator

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    public void changePrice(Long id, BigDecimal newPrice) {
метод не используется, удаляем?

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +    private final List<PriceTimeStamp> priceHistory = new ArrayList<>();
хорошо бы добавить хотя бы парочку продуктов в тестовых данных, у которых есть несколько старых прайсов (в context listener-е)

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/DemoDataServletContextListener.java
> +public class DemoDataServletContextListener implements ServletContextListener {
нужен юнит тест

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/DemoDataServletContextListener.java
> +        if(servletContextEvent.getServletContext().getInitParameter("insertDemoData").equals("true")) {
по канону лучше заменить "true" на Boolean.TRUE.toString()

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +public class ProductDetailsPageServlet extends HttpServlet {
нужен юнит тест

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            request.setAttribute("product", productDao.getProduct(Long.valueOf(url.substring(1))).get());
нужна валидация id продукта чтоб не валился 500 статус при нечисловом параметре

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +        } catch (NoSuchElementException e) {
вместо того, чтобы отлавливать эксепшн, лучше прямо проверять существует ли Optional

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            request.getRequestDispatcher("/WEB-INF/pages/PageNotFound.jsp").forward(request, response);
нужен 404 статус респонса, в данный момент он здесь 200. а еще нужно добавить код продукта в параметры и отобразить на not found странице

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +                SortField.valueOf(sortField),
нужно валидация значений sort field и sort type, иначе при парсинге енама валится исключение и респонс с 500 статусом. в случае некорректного ввода сортировки давай использовать дефолтную сортировку и отображать страницу

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +                SortType.valueOf(sortType)));
^ тут то же самое

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/webapp/WEB-INF/pages/product.jsp
> +    <p>
я б еще добавил кнопочку для возврата на ПЛП

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/main/webapp/WEB-INF/pages/product.jsp
> +    <div class="popup">
давай вынесем часть с price history в тег

2022-02-01 19:39 UTC, WladyslawDryhill commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void testPriceChangeHistory() {
раз мы по сути тестируем только методы класса Product, давай создадим отдельный класс для этого теста

2022-02-02 09:22 UTC, Dima-Makarov commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void testPriceChangeHistory() {
Создал

2022-02-02 17:30 UTC, WladyslawDryhill requested changes
самую малость

2022-02-02 17:30 UTC, WladyslawDryhill commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
добавь плз над классом теста аннотацию @RunWith

2022-02-02 17:30 UTC, WladyslawDryhill commented on src/test/java/com/es/phoneshop/model/product/ProductTest.java
> +public class ProductTest
добавь плз аннотацию @RunWith

2022-02-02 17:30 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                    .sorted(new ProductSearchComparator(queryWordsList)
Тут сперва надо сортировать по сорт филду если он есть, а потом thenComparing уже по совпадениям поиска, иначе результаты невалидные выходят (надо просто поменять местами)

2022-02-02 17:41 UTC, WladyslawDryhill approved these changes
круто

2022-02-02 17:41 UTC, merged