Lecture 3 pdp add to cart
Dima-Makarov/phoneshop-servlet-api pull request #3
Opened 2022-02-04 13:41 UTC by Dima-Makarov

2022-02-08 20:43 UTC, WladyslawDryhill requested changes

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +    private Map<Product, Integer> items;
-> final

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +        this.items = new LinkedHashMap<>();
непотокобезопасная коллекция, советую заменить на подходящую из пакета concurrent, но если тут надо соблюдать последовательность айтемов то хотя бы обернуть в Collections#synchronizedMap

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +    void add(Product p, int quantity) {
несколько операций без синхронизации, советую вынести на уровень выше в сервис под сессионный лок

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +        StringBuilder stringBuilder = new StringBuilder();
небольшая заметка что начиная с Java 5 (вроде бы) компилятор автоматически конкатенацию строк заменяет на StringBuilder, но это так, необязательно рефакторить

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/cart/CartItem.java
> +public class CartItem {
класс не используется?

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/cart/HttpSessionCartService.java
> +    private ProductDao productDao;
-> final

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/cart/HttpSessionCartService.java
> +    public synchronized Cart getCart(HttpServletRequest request) {
синхронизация на глобальный объект будет блокировать все потоки независимо от сессии, нужно сделать лок специфичный для сессии и положить его в атрибут сессии

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/cart/HttpSessionCartService.java
> +    public synchronized void add(Cart cart, Long productId, int quantity) throws OutOfStockException {
тут то же самое касательно лока

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/recentView/HttpSessionRecentViewService.java
> +    public synchronized RecentView getRecentView(HttpServletRequest request) {
тут тоже глобальный лок, нужно как и с корзиной сделать специфичный для сессии

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/recentView/RecentView.java
> +    private Deque<Product> deque;
-> final

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/recentView/RecentView.java
> +        deque = new ArrayDeque<>();
непотокобезопасная коллекция, лучше заменить на аналог из пакета concurrent (например ConcurrentLinkedDeque)

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/recentView/RecentView.java
> +    public void add(Product product) {
несколько операций без синхронизации, советую вынести на уровень выше в сервис под сессионный лок

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +        String quantityString = request.getParameter("quantity");
при пустом параметре валится 500 статус, нужна валидация

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            int quantity = format.parse(quantityString).intValue();
проверь пожалуйста чтоб нельзя было добавлять значения < 1

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            cartService.add(cartService.getCart(request), productId, quantity);
нужна проверка на существование продукта, иначе валится 500 статус

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            doGet(request, response);
нужен редирект чтоб избежать повторной отправки формы и прокинуть error message

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            doGet(request, response);
тут то же самое, нужен редирект

2022-02-08 20:43 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            recentView.add(product);
непотокобезопасное добавление, стоит делать это в сервисе под сессионным локом

2022-02-09 16:13 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +    private Map<Product, Integer> items;
сделал

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +        this.items = new LinkedHashMap<>();
Сделал

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +    void add(Product p, int quantity) {
Вынес

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +        StringBuilder stringBuilder = new StringBuilder();
Если сделать через конкатенацию строк, то Идея советует заменить на StringBuilder: `String concatenation '+' in loop ` поэтому оставлю так

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/cart/CartItem.java
> +public class CartItem {
Снёс)

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/cart/HttpSessionCartService.java
> +    private ProductDao productDao;
Сделал

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/cart/HttpSessionCartService.java
> +    public synchronized void add(Cart cart, Long productId, int quantity) throws OutOfStockException {
Сделал

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/cart/HttpSessionCartService.java
> +    public synchronized Cart getCart(HttpServletRequest request) {
Сделал

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/recentView/RecentView.java
> +    private Deque<Product> deque;
Сделал

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/recentView/HttpSessionRecentViewService.java
> +    public synchronized RecentView getRecentView(HttpServletRequest request) {
Сделал

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/recentView/RecentView.java
> +        deque = new ArrayDeque<>();
Сделал

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +        String quantityString = request.getParameter("quantity");
Занес это все под общий try, теперь 500 не будет

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            int quantity = format.parse(quantityString).intValue();
Сделал

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            cartService.add(cartService.getCart(request), productId, quantity);
Сделал

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            doGet(request, response);
Сделал

2022-02-09 16:14 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            doGet(request, response);
Сделал

2022-02-09 16:15 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            recentView.add(product);
С новой логикой это не нужно

2022-02-09 19:11 UTC, WladyslawDryhill requested changes
еще несколько моментов

2022-02-09 19:11 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            String quantityString = request.getParameter("quantity");
у меня все еще валится 500 статус при пустом значении, потому что в catch блоках не отлавливается NullPointerException(
![image](https://user-images.githubusercontent.com/42232930/153270077-363be51f-6fd7-494c-91b8-f4c8c3f08073.png)

2022-02-09 19:11 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/cart/HttpSessionCartService.java
> +        Lock lock = (Lock) session.getAttribute(LOCK_SESSION_ATTRIBUTE);
тут лучше обезопасить себя и не предполагать что у нас лок уже точно есть в сессии, хоть мы до этого и вызываем getCart(...). сделай пожалуйста такой же процесс получения как и на getCart(...) после фикса

2022-02-09 19:11 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/cart/HttpSessionCartService.java
> +            if (lock == null) {
представь такую ситуацию, есть два потока, первый поток делает getAttribute и получает null, второй поток тоже. однако второй поток попадает в синхронайзд блок раньше первого, создает лок и кладет его в сессию. первый поток попадая после в синхронайзд блок все еще имеет null референс на лок и считает что он еще не создан -> в итоге имеем два разных лока у двух потоков.
поэтому рекомендую сделать так:
проверяем есть ли в сессии лок вне синхронайзд блока, если есть, лочим на нем и не заходим в синхронайзд блок, если нету заходим в синхронайзд блок и **еще раз**  пытаемся взять лок из сессии, если и на этот раз его нет - то только в этом случае создаем его и кладем в сессию. таким образом все будет безопасно)

2022-02-09 19:11 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/recentView/HttpSessionRecentViewService.java
> +            if (lock == null) {
здесь точно такая же ситуация как и в карт сервисе, случай с двумя потоками)

2022-02-09 19:11 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/cart/HttpSessionCartService.java
> +            if (cart == null) {
а потом наш первый поток каким-то образом попадает сюда первым (а это возможно, мы никогда не знаем когда scheduler выключит один поток и отдаст процессорное время другому), создаст корзину и засетает ее в сессию. потом второй поток придет сюда же, у него все еще будет null референс на корзину потому что он получил его давным давно, и в итоге создаст еще одну корзину и перетрет старую. поэтому советую корзину из сессии брать уже после того как мы наконец-то успешно получили лок

2022-02-09 19:11 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/recentView/HttpSessionRecentViewService.java
> +            if (recentView == null) {
и здесь такая же, все по аналогии)

2022-02-10 18:30 UTC, WladyslawDryhill approved these changes

2022-02-10 18:30 UTC, merged