Lecture 4
Dima-Makarov/phoneshop-servlet-api pull request #4
Opened 2022-02-12 16:15 UTC by Dima-Makarov

2022-02-16 17:29 UTC, WladyslawDryhill requested changes

2022-02-16 17:29 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +public class Cart implements Serializable {
давай добавим константу serialVersionUid чтобы в случае незначительных изменения чего-то в классе не было проблем с десериализацией

2022-02-16 17:29 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +public class Product implements Serializable {
и сюда бы тоже serialVersionUid

2022-02-16 17:29 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/model/recentView/RecentView.java
> +public class RecentView implements Serializable {
и сюда бы тоже serialVersionUid

2022-02-16 17:29 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/MiniCartServlet.java
> +public class MiniCartServlet extends HttpServlet {
нет тестов на новые классы?

2022-02-16 17:29 UTC, WladyslawDryhill commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +                int quantity = format.parse(request.getParameter("quantity")).intValue();
сейчас можно добавить отрицательную quantity

2022-02-16 17:29 UTC, WladyslawDryhill commented on src/main/webapp/WEB-INF/pages/productList.jsp
> +                    <form method="post" action="${pageContext.servletContext.contextPath}/products">
параметры сортировки и поиска обнуляются с таким запросом, после добавления в корзину возвращается ПЛП без параметров. по идее если опустить атрибут action то запрос будет делаться на текущий урл (включая все урл параметры)

2022-02-16 17:29 UTC, WladyslawDryhill commented on src/main/webapp/WEB-INF/pages/productList.jsp
> +                                ${param.error}
вывод ошибки и quantity из отправленной формы сейчас не работает (думаю нужно убрать param перед названиями атрибутов)

2022-02-16 17:29 UTC, WladyslawDryhill commented on src/main/webapp/WEB-INF/pages/cart.jsp
> +                        <input name="quantity" value="${entry.value}" class="quantity">
попробуй тут сохранить состояние quantity из формы в случае ошибки валидации. чтоб пользователь видел какое именно неправильное значение он ввел, а то сейчас значение сбрасывается до дефолтного (Андрей вроде в лекции показывал этот момент)

2022-02-17 13:26 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +public class Cart implements Serializable {
Добавил везде

2022-02-17 13:26 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/web/MiniCartServlet.java
> +public class MiniCartServlet extends HttpServlet {
Сделал

2022-02-17 13:26 UTC, Dima-Makarov commented on src/main/webapp/WEB-INF/pages/productList.jsp
> +                    <form method="post" action="${pageContext.servletContext.contextPath}/products">
fixed, удаление action не помогло так как мы делаем редирект, вместо этого в сервлете просто дописал все урл параметры

2022-02-17 13:26 UTC, Dima-Makarov commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +                int quantity = format.parse(request.getParameter("quantity")).intValue();
fixed

2022-02-17 13:26 UTC, Dima-Makarov commented on src/main/webapp/WEB-INF/pages/cart.jsp
> +                        <input name="quantity" value="${entry.value}" class="quantity">
Сделал

2022-02-17 13:26 UTC, Dima-Makarov commented on src/main/webapp/WEB-INF/pages/productList.jsp
> +                                ${param.error}
Да, проблема в этом, исправил

2022-02-17 17:26 UTC, merged